// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vpn.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type VPNProto int32

const (
	VPNProto_NOPREF VPNProto = 0
	VPNProto_UDP    VPNProto = 1
	VPNProto_TCP    VPNProto = 2
)

var VPNProto_name = map[int32]string{
	0: "NOPREF",
	1: "UDP",
	2: "TCP",
}
var VPNProto_value = map[string]int32{
	"NOPREF": 0,
	"UDP":    1,
	"TCP":    2,
}

func (x VPNProto) String() string {
	return proto.EnumName(VPNProto_name, int32(x))
}
func (VPNProto) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_vpn_38c1de627905a14e, []int{0}
}

type VPNStatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VPNStatusRequest) Reset()         { *m = VPNStatusRequest{} }
func (m *VPNStatusRequest) String() string { return proto.CompactTextString(m) }
func (*VPNStatusRequest) ProtoMessage()    {}
func (*VPNStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_vpn_38c1de627905a14e, []int{0}
}
func (m *VPNStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VPNStatusRequest.Unmarshal(m, b)
}
func (m *VPNStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VPNStatusRequest.Marshal(b, m, deterministic)
}
func (dst *VPNStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VPNStatusRequest.Merge(dst, src)
}
func (m *VPNStatusRequest) XXX_Size() int {
	return xxx_messageInfo_VPNStatusRequest.Size(m)
}
func (m *VPNStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VPNStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VPNStatusRequest proto.InternalMessageInfo

type VPNInitRequest struct {
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Port                 string   `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	ProtoPref            VPNProto `protobuf:"varint,3,opt,name=proto_pref,json=protoPref,proto3,enum=pb.VPNProto" json:"proto_pref,omitempty"`
	IpBlock              string   `protobuf:"bytes,4,opt,name=ip_block,json=ipBlock,proto3" json:"ip_block,omitempty"`
	Dns                  string   `protobuf:"bytes,5,opt,name=dns,proto3" json:"dns,omitempty"`
	KeepalivePeriod      string   `protobuf:"bytes,6,opt,name=keepalive_period,json=keepalivePeriod,proto3" json:"keepalive_period,omitempty"`
	KeepaliveTimeout     string   `protobuf:"bytes,7,opt,name=keepalive_timeout,json=keepaliveTimeout,proto3" json:"keepalive_timeout,omitempty"`
	UseLzo               bool     `protobuf:"varint,8,opt,name=use_lzo,json=useLzo,proto3" json:"use_lzo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VPNInitRequest) Reset()         { *m = VPNInitRequest{} }
func (m *VPNInitRequest) String() string { return proto.CompactTextString(m) }
func (*VPNInitRequest) ProtoMessage()    {}
func (*VPNInitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_vpn_38c1de627905a14e, []int{1}
}
func (m *VPNInitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VPNInitRequest.Unmarshal(m, b)
}
func (m *VPNInitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VPNInitRequest.Marshal(b, m, deterministic)
}
func (dst *VPNInitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VPNInitRequest.Merge(dst, src)
}
func (m *VPNInitRequest) XXX_Size() int {
	return xxx_messageInfo_VPNInitRequest.Size(m)
}
func (m *VPNInitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VPNInitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VPNInitRequest proto.InternalMessageInfo

func (m *VPNInitRequest) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *VPNInitRequest) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *VPNInitRequest) GetProtoPref() VPNProto {
	if m != nil {
		return m.ProtoPref
	}
	return VPNProto_NOPREF
}

func (m *VPNInitRequest) GetIpBlock() string {
	if m != nil {
		return m.IpBlock
	}
	return ""
}

func (m *VPNInitRequest) GetDns() string {
	if m != nil {
		return m.Dns
	}
	return ""
}

func (m *VPNInitRequest) GetKeepalivePeriod() string {
	if m != nil {
		return m.KeepalivePeriod
	}
	return ""
}

func (m *VPNInitRequest) GetKeepaliveTimeout() string {
	if m != nil {
		return m.KeepaliveTimeout
	}
	return ""
}

func (m *VPNInitRequest) GetUseLzo() bool {
	if m != nil {
		return m.UseLzo
	}
	return false
}

type VPNUpdateRequest struct {
	IpBlock              string   `protobuf:"bytes,1,opt,name=ip_block,json=ipBlock,proto3" json:"ip_block,omitempty"`
	Dns                  string   `protobuf:"bytes,2,opt,name=dns,proto3" json:"dns,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VPNUpdateRequest) Reset()         { *m = VPNUpdateRequest{} }
func (m *VPNUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*VPNUpdateRequest) ProtoMessage()    {}
func (*VPNUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_vpn_38c1de627905a14e, []int{2}
}
func (m *VPNUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VPNUpdateRequest.Unmarshal(m, b)
}
func (m *VPNUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VPNUpdateRequest.Marshal(b, m, deterministic)
}
func (dst *VPNUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VPNUpdateRequest.Merge(dst, src)
}
func (m *VPNUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_VPNUpdateRequest.Size(m)
}
func (m *VPNUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VPNUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VPNUpdateRequest proto.InternalMessageInfo

func (m *VPNUpdateRequest) GetIpBlock() string {
	if m != nil {
		return m.IpBlock
	}
	return ""
}

func (m *VPNUpdateRequest) GetDns() string {
	if m != nil {
		return m.Dns
	}
	return ""
}

type VPNRestartRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VPNRestartRequest) Reset()         { *m = VPNRestartRequest{} }
func (m *VPNRestartRequest) String() string { return proto.CompactTextString(m) }
func (*VPNRestartRequest) ProtoMessage()    {}
func (*VPNRestartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_vpn_38c1de627905a14e, []int{3}
}
func (m *VPNRestartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VPNRestartRequest.Unmarshal(m, b)
}
func (m *VPNRestartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VPNRestartRequest.Marshal(b, m, deterministic)
}
func (dst *VPNRestartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VPNRestartRequest.Merge(dst, src)
}
func (m *VPNRestartRequest) XXX_Size() int {
	return xxx_messageInfo_VPNRestartRequest.Size(m)
}
func (m *VPNRestartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VPNRestartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VPNRestartRequest proto.InternalMessageInfo

type VPNStatusResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SerialNumber         string   `protobuf:"bytes,2,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	Hostname             string   `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Port                 string   `protobuf:"bytes,4,opt,name=port,proto3" json:"port,omitempty"`
	Cert                 string   `protobuf:"bytes,5,opt,name=cert,proto3" json:"cert,omitempty"`
	CaCert               string   `protobuf:"bytes,6,opt,name=ca_cert,json=caCert,proto3" json:"ca_cert,omitempty"`
	Net                  string   `protobuf:"bytes,7,opt,name=net,proto3" json:"net,omitempty"`
	Mask                 string   `protobuf:"bytes,8,opt,name=mask,proto3" json:"mask,omitempty"`
	CreatedAt            string   `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Proto                string   `protobuf:"bytes,10,opt,name=proto,proto3" json:"proto,omitempty"`
	Dns                  string   `protobuf:"bytes,11,opt,name=dns,proto3" json:"dns,omitempty"`
	ExpiresAt            string   `protobuf:"bytes,12,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CaExpiresAt          string   `protobuf:"bytes,13,opt,name=ca_expires_at,json=caExpiresAt,proto3" json:"ca_expires_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VPNStatusResponse) Reset()         { *m = VPNStatusResponse{} }
func (m *VPNStatusResponse) String() string { return proto.CompactTextString(m) }
func (*VPNStatusResponse) ProtoMessage()    {}
func (*VPNStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_vpn_38c1de627905a14e, []int{4}
}
func (m *VPNStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VPNStatusResponse.Unmarshal(m, b)
}
func (m *VPNStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VPNStatusResponse.Marshal(b, m, deterministic)
}
func (dst *VPNStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VPNStatusResponse.Merge(dst, src)
}
func (m *VPNStatusResponse) XXX_Size() int {
	return xxx_messageInfo_VPNStatusResponse.Size(m)
}
func (m *VPNStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VPNStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VPNStatusResponse proto.InternalMessageInfo

func (m *VPNStatusResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VPNStatusResponse) GetSerialNumber() string {
	if m != nil {
		return m.SerialNumber
	}
	return ""
}

func (m *VPNStatusResponse) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *VPNStatusResponse) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *VPNStatusResponse) GetCert() string {
	if m != nil {
		return m.Cert
	}
	return ""
}

func (m *VPNStatusResponse) GetCaCert() string {
	if m != nil {
		return m.CaCert
	}
	return ""
}

func (m *VPNStatusResponse) GetNet() string {
	if m != nil {
		return m.Net
	}
	return ""
}

func (m *VPNStatusResponse) GetMask() string {
	if m != nil {
		return m.Mask
	}
	return ""
}

func (m *VPNStatusResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *VPNStatusResponse) GetProto() string {
	if m != nil {
		return m.Proto
	}
	return ""
}

func (m *VPNStatusResponse) GetDns() string {
	if m != nil {
		return m.Dns
	}
	return ""
}

func (m *VPNStatusResponse) GetExpiresAt() string {
	if m != nil {
		return m.ExpiresAt
	}
	return ""
}

func (m *VPNStatusResponse) GetCaExpiresAt() string {
	if m != nil {
		return m.CaExpiresAt
	}
	return ""
}

type VPNInitResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VPNInitResponse) Reset()         { *m = VPNInitResponse{} }
func (m *VPNInitResponse) String() string { return proto.CompactTextString(m) }
func (*VPNInitResponse) ProtoMessage()    {}
func (*VPNInitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_vpn_38c1de627905a14e, []int{5}
}
func (m *VPNInitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VPNInitResponse.Unmarshal(m, b)
}
func (m *VPNInitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VPNInitResponse.Marshal(b, m, deterministic)
}
func (dst *VPNInitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VPNInitResponse.Merge(dst, src)
}
func (m *VPNInitResponse) XXX_Size() int {
	return xxx_messageInfo_VPNInitResponse.Size(m)
}
func (m *VPNInitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VPNInitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VPNInitResponse proto.InternalMessageInfo

type VPNUpdateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VPNUpdateResponse) Reset()         { *m = VPNUpdateResponse{} }
func (m *VPNUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*VPNUpdateResponse) ProtoMessage()    {}
func (*VPNUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_vpn_38c1de627905a14e, []int{6}
}
func (m *VPNUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VPNUpdateResponse.Unmarshal(m, b)
}
func (m *VPNUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VPNUpdateResponse.Marshal(b, m, deterministic)
}
func (dst *VPNUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VPNUpdateResponse.Merge(dst, src)
}
func (m *VPNUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_VPNUpdateResponse.Size(m)
}
func (m *VPNUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VPNUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VPNUpdateResponse proto.InternalMessageInfo

type VPNRestartResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VPNRestartResponse) Reset()         { *m = VPNRestartResponse{} }
func (m *VPNRestartResponse) String() string { return proto.CompactTextString(m) }
func (*VPNRestartResponse) ProtoMessage()    {}
func (*VPNRestartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_vpn_38c1de627905a14e, []int{7}
}
func (m *VPNRestartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VPNRestartResponse.Unmarshal(m, b)
}
func (m *VPNRestartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VPNRestartResponse.Marshal(b, m, deterministic)
}
func (dst *VPNRestartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VPNRestartResponse.Merge(dst, src)
}
func (m *VPNRestartResponse) XXX_Size() int {
	return xxx_messageInfo_VPNRestartResponse.Size(m)
}
func (m *VPNRestartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VPNRestartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VPNRestartResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*VPNStatusRequest)(nil), "pb.VPNStatusRequest")
	proto.RegisterType((*VPNInitRequest)(nil), "pb.VPNInitRequest")
	proto.RegisterType((*VPNUpdateRequest)(nil), "pb.VPNUpdateRequest")
	proto.RegisterType((*VPNRestartRequest)(nil), "pb.VPNRestartRequest")
	proto.RegisterType((*VPNStatusResponse)(nil), "pb.VPNStatusResponse")
	proto.RegisterType((*VPNInitResponse)(nil), "pb.VPNInitResponse")
	proto.RegisterType((*VPNUpdateResponse)(nil), "pb.VPNUpdateResponse")
	proto.RegisterType((*VPNRestartResponse)(nil), "pb.VPNRestartResponse")
	proto.RegisterEnum("pb.VPNProto", VPNProto_name, VPNProto_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VPNServiceClient is the client API for VPNService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VPNServiceClient interface {
	Status(ctx context.Context, in *VPNStatusRequest, opts ...grpc.CallOption) (*VPNStatusResponse, error)
	Init(ctx context.Context, in *VPNInitRequest, opts ...grpc.CallOption) (*VPNInitResponse, error)
	Update(ctx context.Context, in *VPNUpdateRequest, opts ...grpc.CallOption) (*VPNUpdateResponse, error)
	Restart(ctx context.Context, in *VPNRestartRequest, opts ...grpc.CallOption) (*VPNRestartResponse, error)
}

type vPNServiceClient struct {
	cc *grpc.ClientConn
}

func NewVPNServiceClient(cc *grpc.ClientConn) VPNServiceClient {
	return &vPNServiceClient{cc}
}

func (c *vPNServiceClient) Status(ctx context.Context, in *VPNStatusRequest, opts ...grpc.CallOption) (*VPNStatusResponse, error) {
	out := new(VPNStatusResponse)
	err := c.cc.Invoke(ctx, "/pb.VPNService/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vPNServiceClient) Init(ctx context.Context, in *VPNInitRequest, opts ...grpc.CallOption) (*VPNInitResponse, error) {
	out := new(VPNInitResponse)
	err := c.cc.Invoke(ctx, "/pb.VPNService/Init", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vPNServiceClient) Update(ctx context.Context, in *VPNUpdateRequest, opts ...grpc.CallOption) (*VPNUpdateResponse, error) {
	out := new(VPNUpdateResponse)
	err := c.cc.Invoke(ctx, "/pb.VPNService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vPNServiceClient) Restart(ctx context.Context, in *VPNRestartRequest, opts ...grpc.CallOption) (*VPNRestartResponse, error) {
	out := new(VPNRestartResponse)
	err := c.cc.Invoke(ctx, "/pb.VPNService/Restart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VPNServiceServer is the server API for VPNService service.
type VPNServiceServer interface {
	Status(context.Context, *VPNStatusRequest) (*VPNStatusResponse, error)
	Init(context.Context, *VPNInitRequest) (*VPNInitResponse, error)
	Update(context.Context, *VPNUpdateRequest) (*VPNUpdateResponse, error)
	Restart(context.Context, *VPNRestartRequest) (*VPNRestartResponse, error)
}

func RegisterVPNServiceServer(s *grpc.Server, srv VPNServiceServer) {
	s.RegisterService(&_VPNService_serviceDesc, srv)
}

func _VPNService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VPNStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VPNServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.VPNService/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VPNServiceServer).Status(ctx, req.(*VPNStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VPNService_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VPNInitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VPNServiceServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.VPNService/Init",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VPNServiceServer).Init(ctx, req.(*VPNInitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VPNService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VPNUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VPNServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.VPNService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VPNServiceServer).Update(ctx, req.(*VPNUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VPNService_Restart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VPNRestartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VPNServiceServer).Restart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.VPNService/Restart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VPNServiceServer).Restart(ctx, req.(*VPNRestartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VPNService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.VPNService",
	HandlerType: (*VPNServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _VPNService_Status_Handler,
		},
		{
			MethodName: "Init",
			Handler:    _VPNService_Init_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _VPNService_Update_Handler,
		},
		{
			MethodName: "Restart",
			Handler:    _VPNService_Restart_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vpn.proto",
}

func init() { proto.RegisterFile("vpn.proto", fileDescriptor_vpn_38c1de627905a14e) }

var fileDescriptor_vpn_38c1de627905a14e = []byte{
	// 619 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x93, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x89, 0x93, 0x3a, 0xc9, 0xf4, 0x9f, 0x3b, 0x4d, 0xa9, 0x09, 0x54, 0x42, 0xe6, 0x52,
	0x8a, 0xd4, 0x88, 0x72, 0xe3, 0x82, 0xa0, 0x14, 0x09, 0xa9, 0x2a, 0x26, 0xb4, 0x5c, 0xad, 0x8d,
	0xb3, 0x14, 0xab, 0x89, 0x77, 0xb1, 0x37, 0x11, 0xea, 0x91, 0x2b, 0x47, 0x1e, 0x8d, 0x13, 0x9c,
	0x79, 0x10, 0x76, 0x67, 0xed, 0xc4, 0x8e, 0xe0, 0x36, 0xfb, 0x9b, 0xd9, 0x4f, 0xb3, 0xdf, 0xcc,
	0x42, 0x77, 0x2e, 0xd3, 0x63, 0x99, 0x09, 0x25, 0xd0, 0x91, 0xa3, 0xfe, 0x83, 0x6b, 0x21, 0xae,
	0x27, 0x7c, 0xc0, 0x64, 0x32, 0x60, 0x69, 0x2a, 0x14, 0x53, 0x89, 0x48, 0x73, 0x5b, 0x11, 0x20,
	0x78, 0x1f, 0xc3, 0x8b, 0x0f, 0x1a, 0xce, 0xf2, 0x21, 0xff, 0x32, 0xe3, 0xb9, 0x0a, 0xbe, 0x3b,
	0xb0, 0xa5, 0xe1, 0xdb, 0x34, 0x51, 0x05, 0xc2, 0x3e, 0x74, 0x3e, 0x8b, 0x5c, 0xa5, 0x6c, 0xca,
	0xfd, 0xc6, 0xc3, 0xc6, 0x61, 0x77, 0xb8, 0x38, 0x23, 0x42, 0x4b, 0x8a, 0x4c, 0xf9, 0x0e, 0x71,
	0x8a, 0xf1, 0x09, 0x00, 0xe9, 0x47, 0x32, 0xe3, 0x9f, 0xfc, 0xa6, 0xce, 0x6c, 0x9d, 0x6c, 0x1c,
	0xcb, 0xd1, 0xb1, 0xd6, 0x0d, 0x4d, 0x62, 0xd8, 0xa5, 0x7c, 0xa8, 0xd3, 0x78, 0x0f, 0x3a, 0x89,
	0x8c, 0x46, 0x13, 0x11, 0xdf, 0xf8, 0x2d, 0x12, 0x69, 0x27, 0xf2, 0x95, 0x39, 0xa2, 0x07, 0xcd,
	0x71, 0x9a, 0xfb, 0x6b, 0x44, 0x4d, 0x88, 0x8f, 0xc1, 0xbb, 0xe1, 0x5c, 0xb2, 0x49, 0x32, 0xe7,
	0x91, 0xe4, 0x59, 0x22, 0xc6, 0xbe, 0x4b, 0xe9, 0xed, 0x05, 0x0f, 0x09, 0xeb, 0x26, 0x76, 0x96,
	0xa5, 0x2a, 0x99, 0x72, 0x31, 0x53, 0x7e, 0x9b, 0x6a, 0x97, 0x1a, 0x97, 0x96, 0xe3, 0x3e, 0xb4,
	0x67, 0x39, 0x8f, 0x26, 0xb7, 0xc2, 0xef, 0xe8, 0x92, 0xce, 0xd0, 0xd5, 0xc7, 0xf3, 0x5b, 0x11,
	0xbc, 0x20, 0x87, 0xae, 0xe4, 0x98, 0x29, 0x5e, 0xda, 0x51, 0xed, 0xb8, 0xf1, 0xcf, 0x8e, 0x9d,
	0x45, 0xc7, 0xc1, 0x2e, 0xec, 0x68, 0x81, 0xa1, 0xbe, 0xc7, 0xb2, 0xd2, 0xd0, 0xe0, 0x97, 0x43,
	0xb4, 0x34, 0x3e, 0x97, 0x7a, 0x24, 0x64, 0x65, 0xc5, 0x62, 0x8a, 0xf1, 0x11, 0x6c, 0xe6, 0xfa,
	0x3d, 0x6c, 0x12, 0xa5, 0xb3, 0xe9, 0x88, 0x67, 0x85, 0xf4, 0x86, 0x85, 0x17, 0xc4, 0x6a, 0xf3,
	0x69, 0xfe, 0x67, 0x3e, 0xad, 0xca, 0x7c, 0x34, 0x8b, 0xb9, 0x66, 0xd6, 0x58, 0x8a, 0x8d, 0x03,
	0x31, 0x8b, 0x08, 0x5b, 0x43, 0xdd, 0x98, 0x9d, 0x9a, 0x84, 0x7e, 0x52, 0xca, 0x4b, 0xe7, 0x4c,
	0x68, 0xae, 0x4f, 0x59, 0x7e, 0x43, 0x4e, 0xe9, 0xeb, 0x26, 0xc6, 0x03, 0x80, 0x38, 0xe3, 0xda,
	0xa4, 0x71, 0xc4, 0x94, 0xdf, 0xa5, 0x4c, 0xb7, 0x20, 0x2f, 0x15, 0xf6, 0x60, 0x8d, 0x26, 0xee,
	0x03, 0x65, 0xec, 0xa1, 0x74, 0x6b, 0x7d, 0x39, 0x5f, 0x2d, 0xc3, 0xbf, 0xca, 0x24, 0xe3, 0xb9,
	0x91, 0xd9, 0xb0, 0x32, 0x05, 0xd1, 0x32, 0x01, 0x6c, 0xea, 0x26, 0x2b, 0x15, 0x9b, 0x54, 0xb1,
	0x1e, 0xb3, 0xb3, 0xb2, 0x26, 0xd8, 0x81, 0xed, 0xc5, 0xfa, 0x5a, 0x63, 0x8b, 0x19, 0x94, 0x43,
	0x2c, 0x60, 0x0f, 0xb0, 0x3a, 0x18, 0x4b, 0x8f, 0x0e, 0xa1, 0x53, 0x2e, 0x29, 0x02, 0xb8, 0x17,
	0xef, 0xc2, 0xe1, 0xd9, 0x1b, 0xef, 0x0e, 0xb6, 0xa1, 0x79, 0xf5, 0x3a, 0xf4, 0x1a, 0x26, 0xb8,
	0x3c, 0x0d, 0x3d, 0xe7, 0xe4, 0xb7, 0x03, 0x60, 0x66, 0xc8, 0xb3, 0x79, 0x12, 0x73, 0x7c, 0x0f,
	0xae, 0x1d, 0x27, 0xf6, 0x8a, 0x4d, 0xaf, 0x7d, 0xab, 0xfe, 0xde, 0x0a, 0x2d, 0xba, 0xe8, 0x7f,
	0xfb, 0xf9, 0xe7, 0x87, 0xd3, 0x43, 0xa4, 0x1f, 0x3a, 0x7f, 0x3a, 0xd0, 0xdf, 0x77, 0x90, 0x5b,
	0xa1, 0x73, 0x68, 0x99, 0x67, 0x20, 0x16, 0x57, 0x2b, 0x5f, 0xb2, 0xbf, 0x5b, 0x63, 0x85, 0xd8,
	0x7d, 0x12, 0xdb, 0x0b, 0xbc, 0xaa, 0x58, 0xa2, 0x2b, 0x9e, 0x37, 0x8e, 0xf0, 0x12, 0x5c, 0xeb,
	0xc0, 0xa2, 0xc1, 0xda, 0x56, 0x2f, 0x1a, 0x5c, 0xb1, 0xe9, 0x80, 0x34, 0xf7, 0x83, 0x5a, 0x83,
	0x33, 0xaa, 0x31, 0xaa, 0x57, 0xd0, 0x2e, 0x2c, 0xc4, 0x52, 0xa0, 0xbe, 0xeb, 0xfd, 0xbb, 0xab,
	0x78, 0xa5, 0xd9, 0xdd, 0xaa, 0x70, 0x66, 0x8b, 0x46, 0x2e, 0x2d, 0xc8, 0xb3, 0xbf, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xba, 0x04, 0x57, 0xbd, 0xce, 0x04, 0x00, 0x00,
}
