// Code generated by protoc-gen-go. DO NOT EDIT.
// source: network.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type NetworkCreateRequest struct {
	Name string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	CIDR string `protobuf:"bytes,2,opt,name=CIDR" json:"CIDR,omitempty"`
	Type string `protobuf:"bytes,3,opt,name=Type" json:"Type,omitempty"`
}

func (m *NetworkCreateRequest) Reset()                    { *m = NetworkCreateRequest{} }
func (m *NetworkCreateRequest) String() string            { return proto.CompactTextString(m) }
func (*NetworkCreateRequest) ProtoMessage()               {}
func (*NetworkCreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *NetworkCreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NetworkCreateRequest) GetCIDR() string {
	if m != nil {
		return m.CIDR
	}
	return ""
}

func (m *NetworkCreateRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type NetworkListRequest struct {
}

func (m *NetworkListRequest) Reset()                    { *m = NetworkListRequest{} }
func (m *NetworkListRequest) String() string            { return proto.CompactTextString(m) }
func (*NetworkListRequest) ProtoMessage()               {}
func (*NetworkListRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

type NetworkDeleteRequest struct {
	Name string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
}

func (m *NetworkDeleteRequest) Reset()                    { *m = NetworkDeleteRequest{} }
func (m *NetworkDeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*NetworkDeleteRequest) ProtoMessage()               {}
func (*NetworkDeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *NetworkDeleteRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type NetworkGetAllTypesRequest struct {
}

func (m *NetworkGetAllTypesRequest) Reset()                    { *m = NetworkGetAllTypesRequest{} }
func (m *NetworkGetAllTypesRequest) String() string            { return proto.CompactTextString(m) }
func (*NetworkGetAllTypesRequest) ProtoMessage()               {}
func (*NetworkGetAllTypesRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

type Network struct {
	Name      string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	CIDR      string `protobuf:"bytes,2,opt,name=CIDR" json:"CIDR,omitempty"`
	Type      string `protobuf:"bytes,3,opt,name=Type" json:"Type,omitempty"`
	CreatedAt string `protobuf:"bytes,4,opt,name=CreatedAt" json:"CreatedAt,omitempty"`
}

func (m *Network) Reset()                    { *m = Network{} }
func (m *Network) String() string            { return proto.CompactTextString(m) }
func (*Network) ProtoMessage()               {}
func (*Network) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *Network) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Network) GetCIDR() string {
	if m != nil {
		return m.CIDR
	}
	return ""
}

func (m *Network) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Network) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type NetworkCreateResponse struct {
	Network *Network `protobuf:"bytes,1,opt,name=Network" json:"Network,omitempty"`
}

func (m *NetworkCreateResponse) Reset()                    { *m = NetworkCreateResponse{} }
func (m *NetworkCreateResponse) String() string            { return proto.CompactTextString(m) }
func (*NetworkCreateResponse) ProtoMessage()               {}
func (*NetworkCreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *NetworkCreateResponse) GetNetwork() *Network {
	if m != nil {
		return m.Network
	}
	return nil
}

type NetworkListResponse struct {
	Networks []*Network `protobuf:"bytes,1,rep,name=Networks" json:"Networks,omitempty"`
}

func (m *NetworkListResponse) Reset()                    { *m = NetworkListResponse{} }
func (m *NetworkListResponse) String() string            { return proto.CompactTextString(m) }
func (*NetworkListResponse) ProtoMessage()               {}
func (*NetworkListResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *NetworkListResponse) GetNetworks() []*Network {
	if m != nil {
		return m.Networks
	}
	return nil
}

type NetworkDeleteResponse struct {
	Network *Network `protobuf:"bytes,1,opt,name=Network" json:"Network,omitempty"`
}

func (m *NetworkDeleteResponse) Reset()                    { *m = NetworkDeleteResponse{} }
func (m *NetworkDeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*NetworkDeleteResponse) ProtoMessage()               {}
func (*NetworkDeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

func (m *NetworkDeleteResponse) GetNetwork() *Network {
	if m != nil {
		return m.Network
	}
	return nil
}

type NetworkGetAllTypesResponse struct {
	Types []string `protobuf:"bytes,1,rep,name=Types" json:"Types,omitempty"`
}

func (m *NetworkGetAllTypesResponse) Reset()                    { *m = NetworkGetAllTypesResponse{} }
func (m *NetworkGetAllTypesResponse) String() string            { return proto.CompactTextString(m) }
func (*NetworkGetAllTypesResponse) ProtoMessage()               {}
func (*NetworkGetAllTypesResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8} }

func (m *NetworkGetAllTypesResponse) GetTypes() []string {
	if m != nil {
		return m.Types
	}
	return nil
}

func init() {
	proto.RegisterType((*NetworkCreateRequest)(nil), "pb.NetworkCreateRequest")
	proto.RegisterType((*NetworkListRequest)(nil), "pb.NetworkListRequest")
	proto.RegisterType((*NetworkDeleteRequest)(nil), "pb.NetworkDeleteRequest")
	proto.RegisterType((*NetworkGetAllTypesRequest)(nil), "pb.NetworkGetAllTypesRequest")
	proto.RegisterType((*Network)(nil), "pb.Network")
	proto.RegisterType((*NetworkCreateResponse)(nil), "pb.NetworkCreateResponse")
	proto.RegisterType((*NetworkListResponse)(nil), "pb.NetworkListResponse")
	proto.RegisterType((*NetworkDeleteResponse)(nil), "pb.NetworkDeleteResponse")
	proto.RegisterType((*NetworkGetAllTypesResponse)(nil), "pb.NetworkGetAllTypesResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for NetworkService service

type NetworkServiceClient interface {
	Create(ctx context.Context, in *NetworkCreateRequest, opts ...grpc.CallOption) (*NetworkCreateResponse, error)
	List(ctx context.Context, in *NetworkListRequest, opts ...grpc.CallOption) (*NetworkListResponse, error)
	Delete(ctx context.Context, in *NetworkDeleteRequest, opts ...grpc.CallOption) (*NetworkDeleteResponse, error)
	GetAllTypes(ctx context.Context, in *NetworkGetAllTypesRequest, opts ...grpc.CallOption) (*NetworkGetAllTypesResponse, error)
}

type networkServiceClient struct {
	cc *grpc.ClientConn
}

func NewNetworkServiceClient(cc *grpc.ClientConn) NetworkServiceClient {
	return &networkServiceClient{cc}
}

func (c *networkServiceClient) Create(ctx context.Context, in *NetworkCreateRequest, opts ...grpc.CallOption) (*NetworkCreateResponse, error) {
	out := new(NetworkCreateResponse)
	err := grpc.Invoke(ctx, "/pb.NetworkService/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkServiceClient) List(ctx context.Context, in *NetworkListRequest, opts ...grpc.CallOption) (*NetworkListResponse, error) {
	out := new(NetworkListResponse)
	err := grpc.Invoke(ctx, "/pb.NetworkService/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkServiceClient) Delete(ctx context.Context, in *NetworkDeleteRequest, opts ...grpc.CallOption) (*NetworkDeleteResponse, error) {
	out := new(NetworkDeleteResponse)
	err := grpc.Invoke(ctx, "/pb.NetworkService/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkServiceClient) GetAllTypes(ctx context.Context, in *NetworkGetAllTypesRequest, opts ...grpc.CallOption) (*NetworkGetAllTypesResponse, error) {
	out := new(NetworkGetAllTypesResponse)
	err := grpc.Invoke(ctx, "/pb.NetworkService/GetAllTypes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for NetworkService service

type NetworkServiceServer interface {
	Create(context.Context, *NetworkCreateRequest) (*NetworkCreateResponse, error)
	List(context.Context, *NetworkListRequest) (*NetworkListResponse, error)
	Delete(context.Context, *NetworkDeleteRequest) (*NetworkDeleteResponse, error)
	GetAllTypes(context.Context, *NetworkGetAllTypesRequest) (*NetworkGetAllTypesResponse, error)
}

func RegisterNetworkServiceServer(s *grpc.Server, srv NetworkServiceServer) {
	s.RegisterService(&_NetworkService_serviceDesc, srv)
}

func _NetworkService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NetworkService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceServer).Create(ctx, req.(*NetworkCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NetworkService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceServer).List(ctx, req.(*NetworkListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NetworkService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceServer).Delete(ctx, req.(*NetworkDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkService_GetAllTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkGetAllTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceServer).GetAllTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NetworkService/GetAllTypes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceServer).GetAllTypes(ctx, req.(*NetworkGetAllTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NetworkService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.NetworkService",
	HandlerType: (*NetworkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _NetworkService_Create_Handler,
		},
		{
			MethodName: "List",
			Handler:    _NetworkService_List_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _NetworkService_Delete_Handler,
		},
		{
			MethodName: "GetAllTypes",
			Handler:    _NetworkService_GetAllTypes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "network.proto",
}

func init() { proto.RegisterFile("network.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 334 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xcd, 0x4e, 0x32, 0x41,
	0x10, 0xe4, 0xef, 0xe3, 0x93, 0x26, 0x7a, 0x68, 0x51, 0x87, 0xf5, 0x27, 0x64, 0x12, 0xa3, 0xf1,
	0xc0, 0x01, 0x4f, 0x5e, 0x20, 0x04, 0x12, 0x63, 0x62, 0x38, 0x8c, 0xbe, 0x00, 0x60, 0x1f, 0x88,
	0x2b, 0xbb, 0xee, 0x8c, 0x1a, 0x1f, 0xc6, 0x77, 0x35, 0xf3, 0xb3, 0xeb, 0x0c, 0xa0, 0x89, 0xf1,
	0xd6, 0x5b, 0xd5, 0x5d, 0x35, 0x5d, 0xe9, 0x85, 0xed, 0x25, 0xa9, 0xb7, 0x24, 0x7b, 0xec, 0xa6,
	0x59, 0xa2, 0x12, 0xac, 0xa4, 0x33, 0x2e, 0xa0, 0x35, 0xb1, 0xe0, 0x28, 0xa3, 0xa9, 0x22, 0x41,
	0xcf, 0x2f, 0x24, 0x15, 0x22, 0xd4, 0x26, 0xd3, 0x27, 0x62, 0xe5, 0x4e, 0xf9, 0xbc, 0x21, 0x4c,
	0xad, 0xb1, 0xd1, 0xcd, 0x58, 0xb0, 0x8a, 0xc5, 0x74, 0xad, 0xb1, 0xfb, 0xf7, 0x94, 0x58, 0xd5,
	0x62, 0xba, 0xe6, 0x2d, 0x40, 0xa7, 0x79, 0xbb, 0x90, 0xca, 0x29, 0xf2, 0x8b, 0xc2, 0x69, 0x4c,
	0x31, 0xfd, 0xe8, 0xc4, 0x0f, 0xa1, 0xed, 0x7a, 0xaf, 0x49, 0x0d, 0xe3, 0x58, 0xcb, 0xca, 0x5c,
	0x68, 0x0e, 0xff, 0x1d, 0xf9, 0x97, 0x57, 0xe2, 0x11, 0x34, 0xec, 0xca, 0x0f, 0x43, 0xc5, 0x6a,
	0x86, 0xf8, 0x02, 0x78, 0x1f, 0xf6, 0x56, 0x72, 0x91, 0x69, 0xb2, 0x94, 0x84, 0xa7, 0x85, 0xbb,
	0x71, 0x6d, 0xf6, 0x9a, 0xdd, 0x74, 0xd6, 0x75, 0x90, 0xc8, 0x39, 0xde, 0x87, 0xdd, 0x20, 0x03,
	0x37, 0x7d, 0x06, 0x5b, 0x0e, 0x96, 0xac, 0xdc, 0xa9, 0xae, 0x8e, 0x17, 0xa4, 0xe7, 0x9f, 0xa7,
	0xf5, 0x3b, 0xff, 0x1e, 0x44, 0x9b, 0x12, 0x74, 0x22, 0x2d, 0xf8, 0x67, 0x00, 0xf3, 0x86, 0x86,
	0xb0, 0x1f, 0xbd, 0x8f, 0x0a, 0xec, 0xb8, 0xa1, 0x3b, 0xca, 0x5e, 0x17, 0x73, 0xc2, 0x01, 0xd4,
	0xed, 0xfe, 0xc8, 0x3c, 0x9b, 0xe0, 0x54, 0xa2, 0xf6, 0x06, 0xc6, 0xfa, 0xf0, 0x12, 0x5e, 0x41,
	0x4d, 0x07, 0x80, 0xfb, 0x5e, 0x93, 0x77, 0x15, 0xd1, 0xc1, 0x1a, 0x5e, 0x8c, 0x0e, 0xa0, 0x6e,
	0x77, 0x0f, 0xbc, 0x83, 0xe3, 0x09, 0xbc, 0xc3, 0xa0, 0x78, 0x09, 0x27, 0xd0, 0xf4, 0x96, 0xc7,
	0x63, 0xaf, 0x77, 0xfd, 0xac, 0xa2, 0x93, 0xef, 0xe8, 0x5c, 0x6f, 0x56, 0x37, 0xbf, 0xcd, 0xe5,
	0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0xeb, 0xb1, 0x53, 0x85, 0x47, 0x03, 0x00, 0x00,
}
